#!/usr/bin/python

import acg

def do_device(card):
	try:
		tag = card.select()
		print "found tag with ID %s"%tag.serial_str
	except acg.ACG_Exception, e:
		print e.msg
		return
	
	for rec in range(0, 0x40):
		for k in [0xaa, 0xbb, 0xff]:
			try:
				card.mifare_login(rec, k)
			except acg.ACG_AuthFailure:
				continue
			except acg.ACG_NoTagInField:
				card.select()
				try:
					card.mifare_login(rec, k)
				except acg.ACG_AuthFailure:
					continue

			try:
				data = card.mifare_readblock(rec)
			except:
				data = "NO DATA"
			print "transport key rec 0x%.2x (%.2X): %s"%(
					rec, k, data)
if __name__ == '__main__':
	for dev in acg.get_devlist():
		print dev.vendor
		print dev.product
		print "%s @ %u baud"%(dev.tty, dev.suggested_baud)
		try:
			card = acg.acg(line=dev.tty,
					baud = dev.suggested_baud,
					tracefile="acgtool.trace")
			do_device(card)
		except acg.ACG_Exception, e:
			print "ERROR: %s"%e.msg
			print
			continue

