#!/usr/bin/python

import acg

def do_device(card):
	try:
		tag = card.select()
		print "Found %s tag with serial 0x%x"%(tag.typename, tag.serial)
		if tag.type == tag.TAG_TYPE_ISO_1443A:
			clevel = {
					tag.CASCADE_LEVEL1: 1,
					tag.CASCADE_LEVEL2: 2,
					tag.CASCADE_LEVEL3: 3,
				}
			if clevel.has_key(tag.cascade):
				print "  Cascade level %u"%clevel[tag.cascade]
		elif tag.type == tag.TAG_TYPE_ISO_1443B:
			pass
	except acg.ACG_Exception, e:
		print e.msg
		return

if __name__ == '__main__':
	for dev in acg.get_devlist():
		print dev.vendor
		print dev.product
		print "%s @ %u baud"%(dev.tty, dev.suggested_baud)
		try:
			card = acg.acg(line=dev.tty,
					baud = dev.suggested_baud,
					tracefile="acgtool.trace")
		except acg.ACG_Exception, e:
			print "ERROR: %s"%e.msg
			print
			continue

		do_device(card)

